#pragma checksum "..\..\..\..\Views\MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "F29D050D81745C354BBDF0B7E56842B50E4C0D7F71E670BE27F390FA1936D544"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Frame_Wpf;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Tekla.Structures.Dialog;
using Tekla.Structures.Dialog.UIControls;


namespace Frame_Wpf {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : Tekla.Structures.Dialog.PluginWindowBase, System.Windows.Markup.IComponentConnector {
        
        
        #line 22 "..\..\..\..\Views\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas nip_Canvas;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\Views\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path path_Frame;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\Views\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_Dimension;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\Views\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path path_Ground;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\..\Views\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog MaterialCatalog;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Frame_Wpf;component/views/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 18 "..\..\..\..\Views\MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).ApplyClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_ApplyClicked);
            
            #line default
            #line hidden
            
            #line 18 "..\..\..\..\Views\MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).CancelClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_CancelClicked);
            
            #line default
            #line hidden
            
            #line 18 "..\..\..\..\Views\MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).ModifyClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_ModifyClicked);
            
            #line default
            #line hidden
            
            #line 18 "..\..\..\..\Views\MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).GetClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_GetClicked);
            
            #line default
            #line hidden
            
            #line 18 "..\..\..\..\Views\MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).OkClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_OkClicked);
            
            #line default
            #line hidden
            
            #line 18 "..\..\..\..\Views\MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).OnOffClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_OnOffClicked);
            
            #line default
            #line hidden
            return;
            case 2:
            this.nip_Canvas = ((System.Windows.Controls.Canvas)(target));
            return;
            case 3:
            this.path_Frame = ((System.Windows.Shapes.Path)(target));
            return;
            case 4:
            this.Path_Dimension = ((System.Windows.Shapes.Path)(target));
            return;
            case 5:
            this.path_Ground = ((System.Windows.Shapes.Path)(target));
            return;
            case 6:
            this.MaterialCatalog = ((Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog)(target));
            
            #line 82 "..\..\..\..\Views\MainWindow.xaml"
            this.MaterialCatalog.SelectClicked += new System.EventHandler(this.MaterialCatalog_SelectClicked);
            
            #line default
            #line hidden
            
            #line 82 "..\..\..\..\Views\MainWindow.xaml"
            this.MaterialCatalog.SelectionDone += new System.EventHandler(this.MaterialCatalog_SelectionDone);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

